import { currentApi } from "../../utils/Api";

const GET_NUMBER_REQUEST = 'GET_INGREDIENTS_REQUEST';
const GET_NUMBER_SUCCESS = 'GET_INGREDIENTS_SUCCESS';
const GET_NUMBER_FAILED = 'GET_INGREDIENTS_FAILED';